### PR TITLE
Fixed some android build errors

### PR DESCRIPTION
**Pull request by jeremyVignelles**
Seems to fix some of the build issues, but I'm now getting namespace conflicts in the MediaPlayerElement sample project.

### CODE REVIEW

**Comment by mfkl** [comment]
Guess Azure pipelines got updated again under out feets uh

**Comment by jeremyVignelles** [comment]
Don't know about azure, but I did update my VS and faced that issue...

**Comment by mfkl** [comment]
```
4>LibVLCSharp\samples\Forms\LibVLCSharp.Forms.MediaElement\LibVLCSharp.Forms.MediaElement.Sample.Android\Resources\Resource.designer.cs(2264,78,2264,122): warning CS0435: The namespace 'LibVLCSharp.Forms.MediaPlayerElement' in 'LibVLCSharp\samples\Forms\LibVLCSharp.Forms.MediaElement\LibVLCSharp.Forms.MediaElement.Sample.Android\MainActivity.cs' conflicts with the imported type 'MediaPlayerElement' in 'LibVLCSharp.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the namespace defined in 'LibVLCSharp\samples\Forms\LibVLCSharp.Forms.MediaElement\LibVLCSharp.Forms.MediaElement.Sample.Android\MainActivity.cs'.
```

**Comment by jeremyVignelles** [comment]
Yeah, that's the warning I was having when I gave up. Weird that it didn't happen before, uh?

**Comment by mfkl** [comment]
> Weird that it didn't happen before, uh?

This might be the reason things change https://github.com/videolan/libvlcsharp/blob/d0e6289838bfc98166c333db6af1707939693dda/samples/Forms/LibVLCSharp.Forms.MediaElement/LibVLCSharp.Forms.MediaElement.Sample/LibVLCSharp.Forms.MediaElement.Sample.csproj#L5

**Comment by mfkl** [comment]
well looks like we're crashing mono on mac now

```
020-08-17T15:46:18.4742720Z 
2020-08-17T15:46:18.4756720Z =================================================================
2020-08-17T15:46:18.4766400Z 	Native Crash Reporting
2020-08-17T15:46:18.4767040Z =================================================================
2020-08-17T15:46:18.4814080Z Got a SIGSEGV while executing native code. This usually indicates
2020-08-17T15:46:18.4819020Z a fatal error in the mono runtime or one of the native libraries 
2020-08-17T15:46:18.4827320Z used by your application.
2020-08-17T15:46:18.4828280Z =================================================================
2020-08-17T15:46:18.4829140Z 
2020-08-17T15:46:18.4829780Z =================================================================
2020-08-17T15:46:18.4830290Z 	Native stacktrace:
2020-08-17T15:46:18.4831330Z =================================================================
2020-08-17T15:46:18.4832810Z 	0x10feb791b - /Library/Frameworks/Mono.framework/Versions/6.4.0/bin/mono-sgen64 : mono_dump_native_crash_info
2020-08-17T15:46:18.4836150Z 	0x10fe507b5 - /Library/Frameworks/Mono.framework/Versions/6.4.0/bin/mono-sgen64 : mono_handle_native_crash
2020-08-17T15:46:18.4837480Z 	0x10feb1aa7 - /Library/Frameworks/Mono.framework/Versions/6.4.0/bin/mono-sgen64 : altstack_handle_and_restore
2020-08-17T15:46:18.4838390Z 	0x0 - Unknown
2020-08-17T15:46:18.4839150Z 	0x1176c7c76 - Unknown
2020-08-17T15:46:18.4850930Z 	0x1125db4e1 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Runtime_CompilerServices_AsyncMethodBuilderCore_MoveNextRunner_InvokeMoveNext_object
2020-08-17T15:46:18.4853690Z 	0x11243fc73 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_ExecutionContext_Run_System_Threading_ExecutionContext_System_Threading_ContextCallback_object_bool
2020-08-17T15:46:18.4855910Z 	0x11247ca2b - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_AwaitTaskContinuation_RunOrScheduleAction_System_Action_bool_System_Threading_Tasks_Task_
2020-08-17T15:46:18.4857430Z 	0x112473a78 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_Task_FinishContinuations
2020-08-17T15:46:18.4858730Z 	0x112472001 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_Task_FinishStageThree
2020-08-17T15:46:18.4860190Z 	0x1125db4e1 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Runtime_CompilerServices_AsyncMethodBuilderCore_MoveNextRunner_InvokeMoveNext_object
2020-08-17T15:46:18.4861830Z 	0x11243fc73 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_ExecutionContext_Run_System_Threading_ExecutionContext_System_Threading_ContextCallback_object_bool
2020-08-17T15:46:18.4864890Z 	0x11247ca2b - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_AwaitTaskContinuation_RunOrScheduleAction_System_Action_bool_System_Threading_Tasks_Task_
2020-08-17T15:46:18.4867190Z 	0x112473a78 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_Task_FinishContinuations
2020-08-17T15:46:18.4868780Z 	0x112472001 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_Task_FinishStageThree
2020-08-17T15:46:18.4870280Z 	0x1125db4e1 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Runtime_CompilerServices_AsyncMethodBuilderCore_MoveNextRunner_InvokeMoveNext_object
2020-08-17T15:46:18.4871990Z 	0x11243fc73 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_ExecutionContext_Run_System_Threading_ExecutionContext_System_Threading_ContextCallback_object_bool
2020-08-17T15:46:18.4873630Z 	0x11247ca2b - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_AwaitTaskContinuation_RunOrScheduleAction_System_Action_bool_System_Threading_Tasks_Task_
2020-08-17T15:46:18.4876010Z 	0x112473a78 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_Task_FinishContinuations
2020-08-17T15:46:18.4877410Z 	0x112472001 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_Task_FinishStageThree
2020-08-17T15:46:18.4878900Z 	0x1125db4e1 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Runtime_CompilerServices_AsyncMethodBuilderCore_MoveNextRunner_InvokeMoveNext_object
2020-08-17T15:46:18.4880470Z 	0x11243fc73 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_ExecutionContext_Run_System_Threading_ExecutionContext_System_Threading_ContextCallback_object_bool
2020-08-17T15:46:18.4897530Z 	0x11247ca2b - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_AwaitTaskContinuation_RunOrScheduleAction_System_Action_bool_System_Threading_Tasks_Task_
2020-08-17T15:46:18.4899080Z 	0x112473a78 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_Task_FinishContinuations
2020-08-17T15:46:18.4900380Z 	0x112472001 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_Task_FinishStageThree
2020-08-17T15:46:18.4901820Z 	0x1125db4e1 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Runtime_CompilerServices_AsyncMethodBuilderCore_MoveNextRunner_InvokeMoveNext_object
2020-08-17T15:46:18.4903420Z 	0x11243fc73 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_ExecutionContext_Run_System_Threading_ExecutionContext_System_Threading_ContextCallback_object_bool
2020-08-17T15:46:18.4905000Z 	0x11247ca2b - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_AwaitTaskContinuation_RunOrScheduleAction_System_Action_bool_System_Threading_Tasks_Task_
2020-08-17T15:46:18.4906770Z 	0x112473a78 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_Task_FinishContinuations
2020-08-17T15:46:18.4908270Z 	0x112472001 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_Task_FinishStageThree
2020-08-17T15:46:18.4910740Z 	0x1125db4e1 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Runtime_CompilerServices_AsyncMethodBuilderCore_MoveNextRunner_InvokeMoveNext_object
2020-08-17T15:46:18.4912770Z 	0x11243fc73 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_ExecutionContext_Run_System_Threading_ExecutionContext_System_Threading_ContextCallback_object_bool
2020-08-17T15:46:18.4914680Z 	0x11247ca2b - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_AwaitTaskContinuation_RunOrScheduleAction_System_Action_bool_System_Threading_Tasks_Task_
2020-08-17T15:46:18.4916430Z 	0x112473a78 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_Task_FinishContinuations
2020-08-17T15:46:18.4917860Z 	0x112472001 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_Task_FinishStageThree
2020-08-17T15:46:18.4919300Z 	0x1125db4e1 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Runtime_CompilerServices_AsyncMethodBuilderCore_MoveNextRunner_InvokeMoveNext_object
2020-08-17T15:46:18.4920970Z 	0x11243fc73 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_ExecutionContext_Run_System_Threading_ExecutionContext_System_Threading_ContextCallback_object_bool
2020-08-17T15:46:18.4922570Z 	0x11247ca2b - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_AwaitTaskContinuation_RunOrScheduleAction_System_Action_bool_System_Threading_Tasks_Task_
2020-08-17T15:46:18.4924010Z 	0x112473a78 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_Task_FinishContinuations
2020-08-17T15:46:18.4925320Z 	0x112472001 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_Task_FinishStageThree
2020-08-17T15:46:18.4926750Z 	0x1125db4e1 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Runtime_CompilerServices_AsyncMethodBuilderCore_MoveNextRunner_InvokeMoveNext_object
2020-08-17T15:46:18.4928620Z 	0x11243fc73 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_ExecutionContext_Run_System_Threading_ExecutionContext_System_Threading_ContextCallback_object_bool
2020-08-17T15:46:18.4930190Z 	0x11247ca2b - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_AwaitTaskContinuation_RunOrScheduleAction_System_Action_bool_System_Threading_Tasks_Task_
2020-08-17T15:46:18.4931590Z 	0x112473a78 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_Task_FinishContinuations
2020-08-17T15:46:18.4932860Z 	0x112472001 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_Task_FinishStageThree
2020-08-17T15:46:18.4934230Z 	0x1125db4e1 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Runtime_CompilerServices_AsyncMethodBuilderCore_MoveNextRunner_InvokeMoveNext_object
2020-08-17T15:46:18.4935830Z 	0x11243fc73 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_ExecutionContext_Run_System_Threading_ExecutionContext_System_Threading_ContextCallback_object_bool
2020-08-17T15:46:18.4937390Z 	0x11247ca2b - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_AwaitTaskContinuation_RunOrScheduleAction_System_Action_bool_System_Threading_Tasks_Task_
2020-08-17T15:46:18.4938840Z 	0x112473a78 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_Task_FinishContinuations
2020-08-17T15:46:18.4940150Z 	0x112472001 - /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/4.5/mscorlib.dll.dylib : System_Threading_Tasks_Task_FinishStageThree
2020-08-17T15:46:18.4941090Z 	0x114f1a733 - Unknown
2020-08-17T15:46:18.4941400Z 
2020-08-17T15:46:18.4941730Z =================================================================
2020-08-17T15:46:18.4942150Z 	Telemetry Dumper:
2020-08-17T15:46:18.4942520Z =================================================================
2020-08-17T15:46:18.4942950Z Pkilling 0x70000909c000 from 0x7000096a5000
2020-08-17T15:46:18.4943320Z Pkilling 0x700007bfb000 from 0x7000096a5000
2020-08-17T15:46:18.4943930Z Pkilling 0x700008e99000 from 0x7000096a5000
2020-08-17T15:46:18.4944340Z Pkilling 0x7000079f8000 from 0x7000096a5000
2020-08-17T15:46:18.4944710Z Pkilling 0x700008c96000 from 0x7000096a5000
2020-08-17T15:46:18.4945060Z Pkilling 0x115329dc0 from 0x7000096a5000
2020-08-17T15:46:18.4956170Z Pkilling 0x7000077f5000 from 0x7000096a5000
2020-08-17T15:46:18.4959440Z Pkilling 0x700008a93000 from 0x7000096a5000
2020-08-17T15:46:18.4960350Z Pkilling 0x7000075f2000 from 0x7000096a5000
2020-08-17T15:46:18.4975120Z Pkilling 0x700009cae000 from 0x7000096a5000
2020-08-17T15:46:18.4975780Z Pkilling 0x700008890000 from 0x7000096a5000
2020-08-17T15:46:18.4976240Z Pkilling 0x7000073ef000 from 0x7000096a5000
2020-08-17T15:46:18.4976660Z Pkilling 0x700009aab000 from 0x7000096a5000
2020-08-17T15:46:18.4977060Z Pkilling 0x70000868d000 from 0x7000096a5000
2020-08-17T15:46:18.4977460Z Pkilling 0x7000071ec000 from 0x7000096a5000
2020-08-17T15:46:18.4977930Z Pkilling 0x700006ee3000 from 0x7000096a5000
2020-08-17T15:46:18.4978380Z Pkilling 0x700008407000 from 0x7000096a5000
2020-08-17T15:46:18.4978830Z Pkilling 0x7000098a8000 from 0x7000096a5000
2020-08-17T15:46:18.4979240Z Pkilling 0x700008204000 from 0x7000096a5000
2020-08-17T15:46:18.4979690Z Pkilling 0x7000094a2000 from 0x7000096a5000
2020-08-17T15:46:18.4980120Z Pkilling 0x700008001000 from 0x7000096a5000
2020-08-17T15:46:18.4980540Z Pkilling 0x70000929f000 from 0x7000096a5000
2020-08-17T15:46:18.4980970Z Pkilling 0x700007dfe000 from 0x7000096a5000
2020-08-17T15:46:18.5208460Z Entering thread summarizer pause from 0x7000096a5000
2020-08-17T15:46:18.5404000Z Finished thread summarizer pause from 0x7000096a5000.
2020-08-17T15:46:18.6390650Z Installing Xamarin.Android.Support.Compat 26.1.0.1.
2020-08-17T15:46:18.6494200Z Installing Xamarin.Android.Support.Vector.Drawable 26.1.0.1.
2020-08-17T15:46:18.6595850Z Installing Xamarin.Android.Support.Animated.Vector.Drawable 26.1.0.1.
2020-08-17T15:46:18.6696960Z Installing System.ValueTuple 4.4.0.
2020-08-17T15:46:18.6801990Z Installing CommonServiceLocator 1.3.
2020-08-17T15:46:18.8311430Z 
2020-08-17T15:46:18.8312810Z Waiting for dumping threads to resume
2020-08-17T15:46:19.8580890Z 
2020-08-17T15:46:19.8581980Z =================================================================
2020-08-17T15:46:19.8584780Z 	External Debugger Dump:
2020-08-17T15:46:19.8585350Z =================================================================
2020-08-17T15:46:35.2977020Z (lldb) command source -s 0 '/tmp/mono-gdb-commands.1574'
2020-08-17T15:46:35.2978340Z Executing commands in '/tmp/mono-gdb-commands.1574'.
2020-08-17T15:46:35.2979110Z (lldb) process attach --pid 1574
2020-08-17T15:46:35.6250110Z error: attach failed: Error 1
2020-08-17T15:46:35.6441270Z 
2020-08-17T15:46:35.6443720Z =================================================================
2020-08-17T15:46:35.6446650Z 	Basic Fault Address Reporting
2020-08-17T15:46:35.6447160Z =================================================================
2020-08-17T15:46:35.6447570Z instruction pointer is NULL, skip dumping
2020-08-17T15:46:35.6447980Z =================================================================
2020-08-17T15:46:35.6448350Z 	Managed Stacktrace:
2020-08-17T15:46:35.6448720Z =================================================================
2020-08-17T15:46:35.6449150Z =================================================================
2020-08-17T15:46:35.6614210Z An error occurred when executing task 'Restore-NuGet-Packages'.
2020-08-17T15:46:35.6691820Z Error: One or more errors occurred. (NuGet: Process returned an error (exit code 134).)
2020-08-17T15:46:35.6695790Z 	NuGet: Process returned an error (exit code 134).
2020-08-17T15:46:35.7899180Z 
2020-08-17T15:46:35.8091720Z ##[error]Bash exited with code '1'.
2020-08-17T15:46:35.8112760Z ##[section]Finishing: Build all
```

**Pull request merged**
