### PR TITLE
initial versioning strategy doc

### PR DESCRIPTION
**Pull request by mfkl**
Feel free to contribute your opinions.

More info: https://code.videolan.org/videolan/LibVLCSharp/issues/22

### CODE REVIEW

**Comment by jeremyVignelles** [comment]
A word about 0.x versions?
VLC 3.0 is a LTS branch, while 4.0 will likely not be, as far as I understand. (maybe j-b can confirm this)
This means that VLC 5.0 can be released and 3.0 will still be supported.
Should we adopt the same scheme?

**Comment by jeremyVignelles** [comment]
I was thinking about saying "0.x are based on libvlc 3 and may contain breaking changes until LibVlcSharp 3.0 is released

**Comment by jeremyVignelles** [comment]
LGTM

**Comment by mfkl** [comment]
https://github.com/videolan/libvlcsharp/commit/8566221ee0f0654b63b176c2892d98b455e32c20

**Pull request closed without merging**
