### PR TITLE
A way to support ScrollViewer controls and Modify Sample

### PR DESCRIPTION
**Pull request by afunc233**
### Description of Change ###

[ForegroundWindow.cs](https://github.com/afunc233/libvlcsharp/blob/master/src/LibVLCSharp.WPF/ForegroundWindow.cs)
[Example2.xaml](https://github.com/afunc233/libvlcsharp/blob/master/samples/LibVLCSharp.WPF.Sample/Example2.xaml)

### Issues Resolved ### 

- fixes [#524](https://code.videolan.org/videolan/LibVLCSharp/-/issues/524)

### API Changes ###

 
 None

### Platforms Affected ### 

- WPF

### Behavioral/Visual Changes ###

None

#### Before
before

#### After
after

### Testing Procedure ###

Run LibVlcSharp WPF sample and Drag the ScrollBar

### PR Checklist ###

- [ ] Rebased on top of the target branch at time of PR
- [ ] Changes adhere to coding standard

### CODE REVIEW

**Comment by afunc233** [comment]
just a dirty solution

**Comment by mfkl** [comment]
> just a dirty solution

What makes you think it is dirty?

Did you try other use cases with your code to make sure it does not break existing functionality?

**Comment by afunc233** [comment]
> > just a dirty solution
> 
> What makes you think it is dirty?
> 
> Did you try other use cases with your code to make sure it does not break existing functionality?
1. it's  slow
2. i find a Scenes will broke my solution, the parameter of   SetWindowRgn maybe  Pixel but PR is dpi ，it means PR only works in zoom and layout is 100% 
image

**Comment by mfkl** [comment]
Try implementing this https://stackoverflow.com/a/14099937/4064749 instead maybe? Seems to work for people

**Comment by mfkl** [comment]
Feel free to re-open or discuss on gitlab. Closing for now.

**Pull request closed without merging**
