### PR TITLE
UWP support

### PR DESCRIPTION
**Pull request by mfkl**
See https://code.videolan.org/videolan/LibVLCSharp/issues/116

### CODE REVIEW

**Comment by mfkl** [comment]
No audio currently. This fails for some reason https://github.com/videolan/vlc-3.0/blob/5967a6469a86f43131021d8a089e98670b952bef/modules/audio_output/wasapi.c#L502

**Comment by jeremyVignelles** [comment]
What's the error code there?

**Comment by mfkl** [comment]
`wasapi generic error: cannot activate client (error 0x80070057)`. so `E_INVALIDARG`

**Comment by jeremyVignelles** [comment]
No sound here either with the gitlab nightly. Didn't check, but I assume that I had the same error.

The doc here doesn't really help : https://docs.microsoft.com/en-us/windows/desktop/api/mmdeviceapi/nf-mmdeviceapi-immdevice-activate
> E_INVALIDARG : The pActivationParams parameter must be NULL for the specified interface; or pActivationParams points to invalid data.

**Comment by mfkl** [comment]
Superseded by https://github.com/videolan/libvlcsharp/pull/44

**Pull request closed without merging**
