### PR TITLE
WinForms/WPF .NET Core 3 support for LibVLCSharp

### PR DESCRIPTION
**Pull request by dashkan**
### Description of Change ###

Add support for .net core 3.0 winforms and wpf

### Issues Resolved ### 

- fixes #140

### API Changes ###

 
 None

### Platforms Affected ### 

New platform added
- netcoreapp3.0

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### PR Checklist ###

- [ ] Rebased on top of the target branch at time of PR
- [X] Changes adhere to coding standard

### CODE REVIEW

**Comment by mfkl** [comment]
Hi @dashkan,

Thank you for your contribution!

Can you rebase your branch on latest master please? I updated the CI so that the Windows build hopefully passes.

Additionally, it'd be awesome if you could add a small sample to the `Samples` folder showing either a WinForms or WPF .NET Core 3 app using the new build target.

Thanks!

**Comment by dashkan** [comment]
@mfkl ,

The update to MSBuild.Sdk.Extras is breaking the netcoreapp3.0 desktop builds. Running ```dotnet restore -f netcoreapp3.0```  and ```dotnet build -f netcoreapp3.0``` hangs. I don't know enough about MSBuild.Sdk.Extras to help. 

Also found that EnsureVersionsMatch in [Core.cs](https://github.com/videolan/libvlcsharp/blob/e16e5e83dd5c26d9ba598bd3d780ff92b99812f1/LibVLCSharp/Shared/Core.cs#L90) fails because of a version mismatch. libvlcMajorVersion is 3 while libvlcsharpMajorVersion is 4. There is no version 4 of VideoLAN.LibVLC.Windows nuget package. Need guidance on this issue.

If I revert MSBuild.Sdk.Extras to 2.0.24 and change the version of LibVLCSharp.csproj to 3.x I am able to build and run the winforms sample application targeting netcoreapp3.0.

**Comment by jeremyVignelles** [comment]
@dashkan: if dotnet restore hangs, it's more likely a network issue. How long did you wait?

**Comment by mfkl** [comment]
> Also found that EnsureVersionsMatch in Core.cs fails because of a version mismatch. libvlcMajorVersion is 3 while libvlcsharpMajorVersion is 4. There is no version 4 of VideoLAN.LibVLC.Windows nuget package. Need guidance on this issue.

I retargeted your PR to `3.x`. Can you rebase your commit on top of `3.x` please? `3.x` should be the main branch of the repo, not `master`, that's my mistake.

libvlcsharp 4 / libvlc 4 is indeed not released yet so no need to worry about this right now.

Can you add your netcore3 sample so I can investigate locally?

**Pull request closed without merging**
