### PR TITLE
Initial opengl callback interop

### PR DESCRIPTION
**Pull request by mfkl**
This adds new interop callbacks for opengl rendering. It will allow integration with game engines and other graphics libraries such as https://github.com/mellinoe/veldrid.

For now, it's opengl/opengles only (no direct3D yet).

I'd like for a sample to be added to this PR before merging.

Nightly or libvlc 4.0 only.

### CODE REVIEW

**Comment by mfkl** [comment]
Waiting for libvlc API to stabilize to finish this.

**Comment by Ch4rg3r** [comment]
Couldn't we make the OpenGL implementation (and Veldrid) availible by using the Veldrid library and their SDL2/OpenGL implementation? They have native support for all necessary classes/functions. 
This wouldn'n be too difficult.

**Comment by mfkl** [comment]
> Couldn't we make the OpenGL implementation (and Veldrid) availible by using the Veldrid library and their SDL2/OpenGL implementation?

No, we want libvlc to do the decoding and provide the decoded textures (which could be sent after that to veldrid for display, sure). Still waiting for that API to stabilize.

**Comment by mfkl** [comment]
Closing that for now.

**Pull request closed without merging**
