### PR TITLE
Update Core.cs

### PR DESCRIPTION
**Pull request by yasinsensoy**
This solves the character problem.

### CODE REVIEW

**Comment by jeremyVignelles** [comment]
Congrats for your first PR 👏 🎉 

Did you try the change? Does it solve your issue?
I think you would also need to rename `LoadLibrary` to `LoadLibraryW` to use the UTF-16 variant of the Win32 API

**Comment by yasinsensoy** [comment]
> Congrats for your first PR 👏 🎉
> 
> Did you try the change? Does it solve your issue?
> I think you would also need to rename to to use the UTF-16 variant of the Win32 `LoadLibrary``LoadLibraryW`API

Thanks. I tried it solved the problem.

**Review by jeremyVignelles — APPROVED** [review]
LGTM then

**Comment by yasinsensoy** [comment]
Will this change apply to NuGet?

**Comment by jeremyVignelles** [comment]
Only after it's merged and after we release a new 3.x package

**Comment by yasinsensoy** [comment]
Understood thanks

**Comment by mfkl** [comment]
> When the ExactSpelling field is false, as it is by default in C++ and C#, platform invoke searches for the mangled name first (MessageBoxW), then the unmangled alias (MessageBox) if the mangled name is not found. Notice that Unicode name-matching behavior differs from ANSI name-matching behavior.

https://docs.microsoft.com/en-us/dotnet/framework/interop/specifying-a-character-set

Edited your patch so that `LoadLibraryW` is clearly specified in the code, as it is the one being used.

Merged, thanks.

**Pull request closed without merging**
